# RWTH-PHOENIX-2014T Mediapipe and I3D Features Preprocessing and Exploration

In [10]:
os.chdir("/ocean/projects/cis250077p/apham8/asl-cnn-transformer/")

In [11]:
import numpy as np
import torch
import pandas as pd
import os

## Folder Paths

In [38]:
FEATURES_PATH = os.path.join("data", "external", "rwth-phoenix-2014t-i3d-mediapipe")
TSV_PATH = os.path.join(FEATURES_PATH, "tsv files_rwth phoenix 2014t", "tsv files")
I3D_PATH = os.path.join(FEATURES_PATH, "i3d_features_rwth phoenix 2014t", "i3d_features_rwth phoenix 2014t")
MEDIAPIPE_PATH = os.path.join(FEATURES_PATH, "mediapipe_features_rwth phoenix weather 2014t", "mediapipe_features")

## Load train DF

In [30]:
df = pd.read_csv(os.path.join(TSV_PATH, "cvpr23.fairseq.i3d.train.how2sign.tsv"), sep = '\t')
df.head()

,translation,id,signs_file,signs_offset,signs_length,signs_type,signs_lang,translation_tokenized,translation_lang,glosses,topic,signer_id,signs_mediapipe_file
0,und nun die wettervorhersage für morgen donner...,11August_2010_Wednesday_tagesschau-1,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...,0,86,i3d,dgs,und nun die wettervorhersage für morgen donner...,de,NaN,NaN,Signer08,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...
1,mancherorts regnet es auch länger und ergiebig...,11August_2010_Wednesday_tagesschau-4,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...,0,126,i3d,dgs,mancherorts regnet es auch länger und ergiebig...,de,NaN,NaN,Signer08,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...
2,im nordwesten bleibt es heute nacht meist troc...,11August_2010_Wednesday_tagesschau-5,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...,0,168,i3d,dgs,im nordwesten bleibt es heute nacht meist troc...,de,NaN,NaN,Signer08,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...
3,auch am tag gibt es verbreitet zum teil kräfti...,11August_2010_Wednesday_tagesschau-6,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...,0,185,i3d,dgs,auch am tag gibt es verbreitet zum teil kräfti...,de,NaN,NaN,Signer08,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...
4,größere wolkenlücken finden sich vor allem im ...,11August_2010_Wednesday_tagesschau-7,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...,0,71,i3d,dgs,größere wolkenlücken finden sich vor allem im ...,de,NaN,NaN,Signer08,/media/rmedu/F/RabeyaSafaeid/German/slt_how2si...

In [31]:
df.columns

Index(['translation', 'id', 'signs_file', 'signs_offset', 'signs_length',
       'signs_type', 'signs_lang', 'translation_tokenized', 'translation_lang',
       'glosses', 'topic', 'signer_id', 'signs_mediapipe_file'],
      dtype='object')

In [32]:
df.describe()

       signs_offset  signs_length  glosses  topic
count        7096.0   7096.000000      0.0    0.0
mean            0.0    116.594419      NaN    NaN
std             0.0     49.859426      NaN    NaN
min             0.0     16.000000      NaN    NaN
25%             0.0     83.000000      NaN    NaN
50%             0.0    112.000000      NaN    NaN
75%             0.0    144.000000      NaN    NaN
max             0.0    475.000000      NaN    NaN

# Datatypes of DFs

In [33]:
df.dtypes

translation               object
id                        object
signs_file                object
signs_offset               int64
signs_length               int64
signs_type                object
signs_lang                object
translation_tokenized     object
translation_lang          object
glosses                  float64
topic                    float64
signer_id                 object
signs_mediapipe_file      object
dtype: object

## Find missing/NA entries in dataset

In [34]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

                       Total  Percent
glosses                 7096      1.0
topic                   7096      1.0
translation                0      0.0
id                         0      0.0
signs_file                 0      0.0
signs_offset               0      0.0
signs_length               0      0.0
signs_type                 0      0.0
signs_lang                 0      0.0
translation_tokenized      0      0.0
translation_lang           0      0.0
signer_id                  0      0.0
signs_mediapipe_file       0      0.0

## Loading Mediapipe landmarks sample

In [47]:
# Only pose landmarks?
mediapipe_sample = np.load(os.path.join(MEDIAPIPE_PATH, "test", "25October_2010_Monday_tagesschau-17.npy"))
mediapipe_sample.shape

(181, 33, 3)

## Get average max and min for x, y, z components

In [49]:
mediapipe_sample.max(axis=0).mean(axis=0)

array([0.5079852 , 0.86754654, 0.01141397])

In [50]:
mediapipe_sample.min(axis=0).mean(axis=0)

array([ 0.34130887,  0.66828496, -0.95495025])

## Loading I3D Sample

In [48]:
i3d_sample = np.load(os.path.join(I3D_PATH, "test", "25October_2010_Monday_tagesschau-17.npy"))
i3d_sample.shape

(166, 1024)